repc: Fix generated code for class with one SIGNAL
With this .rep file:
class MyClass
{
    SIGNAL(foo())
}

We got the following error:
.moc/../rep_classwithsignalonlytest_merged.h:153:11: error: class
‘MyClassSourceAPI<ObjectType>’ does not have any field named
‘methodArgTypes’
         , methodArgTypes{}

Fix this by not generating the code for the member initializers at all. The
members are initialized within the ctor anyway

Regression introduced by fc881f28987764e48237d648622e6227c2ad3237

Change-Id: I8141aa799e02408a6484a13a28064813a2dc5007
Reviewed-by: Continuous Integration (KDAB) <build@kdab.com>
Reviewed-by: Brett Stottlemyer <bstottle@ford.com>