Improve error reporting
Error reporting is now much closer to what you'd expect from a compiler:

Output example:
repc:
/home/kfunk/devel/src/qtremoteobjects/tests/auto/integration/engine.rep:14:
error: Unknown token encountered

Change-Id: I7ae559dc607846d8848a3af99ad184b0b7822f0d
Reviewed-by: Continuous Integration (KDAB) <build@kdab.com>
Reviewed-by: Brett Stottlemyer <bstottle@ford.com>